### ISSUE TITLE
Design Brainstorm For Lodestar Browser Apps/Tools Hub Page

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar.chainsafe.io#1]
I am making this issue to discuss and brainstorm ideas for an app to bring together our lodestar web browser apps into a hub page.  This would be composed of simpleserialize.com and bls-keygen.com, for now, with more to come in the future, such as the ENR app that was discussed in the most recent Lodestar planning meeting.  Aside from having a page that has links to the apps themselves, I'm not sure what else should be in this page or how people would like this page to look.  Please let me know what you would like to see in this app.

@ChainSafe/eth2-0

**Comment by GregTheGreek** [comment]
A simple starting point was the https://github.com/linuxserver/Heimdall dashboard look, where we can provide more detail about the project above the icons etc...

**Comment by 3xtr4t3rr3str14l** [comment]
@GregTheGreek so it should just be something that has, say, a title at the top with a description, and then a list of the apps with maybe an icon and description for each app?  and then when you click, say, the icon, it opens up the app in a new window?  how does that sound?  is there any base-level functionality in there that i may have missed?

**Comment by GregTheGreek** [comment]
I think thats perfect for the time being, itterate from there

**Comment by 3xtr4t3rr3str14l** [comment]
@ChainSafe/eth2-0  I need to make a staging site for this, but here's the design I got so far.  thoughts?  the green buttons you click and they open the app in a new tab

![Screenshot from 2020-06-12 16-37-53](https://user-images.githubusercontent.com/32028745/84548415-29eda480-accb-11ea-83cf-31e6ae617620.png)

**Comment by twoeths** [comment]
That looks great to me.

**Comment by GregTheGreek** [comment]
I think this a good start :)

**Comment by 3xtr4t3rr3str14l** [comment]
@GregTheGreek what do you think should change about it?  any thoughts in particular?

**Comment by GregTheGreek** [comment]
Think how to add some spice to the buttons

**Comment by 3xtr4t3rr3str14l** [comment]
@GregTheGreek do we have some sort of iconography that we can use for the individual apps, possibly?  alternatively, i can just have a box with a title and a description of the app, with maybe the button below that, or something similar

**Comment by wemeetagain** [comment]
👍 to having a description for each app

**Comment by GregTheGreek** [comment]
@sweetpea22

**Comment by sweetpea22** [comment]
Hmm, here's one way to do it if the user is meant to get their info from those respective web apps: 
 <img width="1012" alt="Screen Shot 2020-06-15 at 7 32 42 PM" src="https://user-images.githubusercontent.com/47398578/84715628-fe72f000-af3e-11ea-9a02-28ad285ed32f.png">

Another way could be to use collapsible buttons or tabbed menu to toggle dense info.
https://getbootstrap.com/docs/4.3/components/collapse/

**Comment by sweetpea22** [comment]
Heimdall dashboard looks nice, similar 'card' style UI possibilities: 
 
<img width="799" alt="Screen Shot 2020-06-15 at 7 51 22 PM" src="https://user-images.githubusercontent.com/47398578/84716617-9f62aa80-af41-11ea-8da6-9fc7c0d0f651.png">

<img width="1358" alt="Screen Shot 2020-06-15 at 7 55 01 PM" src="https://user-images.githubusercontent.com/47398578/84716817-32034980-af42-11ea-8a7a-50d133e833e1.png">

**Comment by 3xtr4t3rr3str14l** [comment]
ok, made some modifications.  you can see them here (this will be used as the staging site for now for future changes in this cycle too):
https://objective-brahmagupta-ce8d42.netlify.app/

thoughts?

**Comment by sweetpea22** [comment]
@3xtr4t3rr3str14l @GregTheGreek custom iconography 👇🏼
<img width="1456" alt="Screen Shot 2020-06-20 at 10 44 40 PM" src="https://user-images.githubusercontent.com/47398578/85215511-b3464c00-b347-11ea-8116-c2faa95a3a70.png">

**Comment by 3xtr4t3rr3str14l** [comment]
@GregTheGreek , @3xtr4t3rr3str14l , I liked @sweetpea22 's styling, so i went with that instead in addition to incorporating the icons.  what do y'all think?
https://objective-brahmagupta-ce8d42.netlify.app/

**Comment by GregTheGreek** [comment]
Very clean! What's everyone's thoughts on making those official icons on the respective sites ??

**Comment by GregTheGreek** [comment]
I think the icons could be centred further, on my computer it seems to be pushing upward

**Comment by GregTheGreek** [comment]
also can you `_target` all the links?

**Comment by 3xtr4t3rr3str14l** [comment]
@GregTheGreek just pushed changes for _target and vertical centering

**Comment by GregTheGreek** [comment]
I feel like we need to add a paragraph to some sort to explain what someone is looking at. otherwsie looks really great!

**Comment by 3xtr4t3rr3str14l** [comment]
@GregTheGreek i figured the right-hand header tagline and the descriptions for the websites would help explain.  do you think we need to maybe add more text to the right-hand header tagline or to the descriptions?

**Comment by GregTheGreek** [comment]
I was thinking more on the left side just explaining what Lodestar is

**Comment by sweetpea22** [comment]
> I was thinking more on the left side just explaining what Lodestar is

Why not make the text smaller and turn it into a paragraph on the right? Another possibility can be putting it top-center above the cards.

> Very clean! What's everyone's thoughts on making those official icons on the respective sites ??

The ENR pic might look weird if it's sized too small, other than that i think they're fine
